
server:
  http_listen_port: 9080

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: trivy-scans
    static_configs:
      - targets:
          - localhost
        labels:
          job: trivy
          __path__: /home/mario/kali-test-clean-fresh/*.json
