version: "3.8"

services:
  app:
    build: .
    container_name: devsecops-app
    image: ${DOCKERHUB_USERNAME}/kali-test:latest
    ports:
      - "8000:8000"
    networks:
      - monitoring
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_PUSHGATEWAY=http://pushgateway:9091

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
